// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AchievementsService is a game's achievements, for the interface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as achievements$0 from "../achievements/models.js";

/**
 * Get returns a game's achievements. Results are reused while the files
 * they came from haven't changed; fresh reads them again.
 */
export function Get(id: number, fresh: boolean): $CancellablePromise<achievements$0.List> {
    return $Call.ByID(2360103754, id, fresh);
}
