// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AddonsService manages add-ons and asks them about games.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add asks for an addon.json and adds that add-on (turned off).
 */
export function Add(): $CancellablePromise<$models.AddonView> {
    return $Call.ByID(2795274992);
}

/**
 * Disable turns an add-on off.
 */
export function Disable(id: string): $CancellablePromise<$models.AddonView> {
    return $Call.ByID(881970999, id);
}

/**
 * Enable turns an add-on on, approving its program as it is now (sha256
 * must match what the user was shown).
 */
export function Enable(id: string, sha256: string): $CancellablePromise<$models.AddonView> {
    return $Call.ByID(2224608146, id, sha256);
}

/**
 * ForGame asks every enabled add-on about a game: badges, lines and actions.
 */
export function ForGame(id: number): $CancellablePromise<$models.AddonGame[] | null> {
    return $Call.ByID(494189446, id);
}

/**
 * List returns every add-on found, working or not.
 */
export function List(): $CancellablePromise<$models.AddonView[] | null> {
    return $Call.ByID(2845432501);
}

/**
 * OpenFolder shows the add-ons folder.
 */
export function OpenFolder(): $CancellablePromise<void> {
    return $Call.ByID(1368854989);
}

/**
 * Remove forgets an add-on. Its program stays where it is.
 */
export function Remove(id: string): $CancellablePromise<void> {
    return $Call.ByID(2905516473, id);
}

/**
 * RunAction runs an add-on's action for a game and returns its message.
 * Progress lines arrive as "addon:progress" events.
 */
export function RunAction(id: number, addon: string, action: string): $CancellablePromise<string> {
    return $Call.ByID(346823100, id, addon, action);
}
