// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LaunchService starts games and follows them while they run.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launch$0 from "../launch/models.js";

/**
 * Answer answers a question a hook asked.
 */
export function Answer(questionID: number, option: string): $CancellablePromise<void> {
    return $Call.ByID(3717002695, questionID, option);
}

/**
 * Cancel stops a launch that hasn't reached the game yet.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(794141971);
}

/**
 * CloseOverlay hides the in-game overlay.
 */
export function CloseOverlay(): $CancellablePromise<void> {
    return $Call.ByID(1717295753);
}

/**
 * OpenMain opens the main window (from the overlay), leaving the game running.
 */
export function OpenMain(): $CancellablePromise<void> {
    return $Call.ByID(2503307204);
}

/**
 * Play starts a game: hooks first, then the game, then it is followed
 * until it exits.
 */
export function Play(id: number): $CancellablePromise<void> {
    return $Call.ByID(3166904315, id);
}

/**
 * PlayFromArgs starts the game named by "--play <id>", if any. The
 * interface isn't opened for it; the game comes first.
 */
export function PlayFromArgs(args: string[] | null): $CancellablePromise<boolean> {
    return $Call.ByID(970986162, args);
}

/**
 * QuitGame ends the running game's processes right away.
 */
export function QuitGame(): $CancellablePromise<void> {
    return $Call.ByID(2149891540);
}

/**
 * Route tells how a game would start now: direct, store or steamInput.
 */
export function Route(id: number): $CancellablePromise<string> {
    return $Call.ByID(468420342, id);
}

/**
 * Session returns the current (or last) game session.
 */
export function Session(): $CancellablePromise<launch$0.Session> {
    return $Call.ByID(3158055791);
}

/**
 * SetUIMode tells the core which mode the interface shows.
 */
export function SetUIMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(303298758, mode);
}

/**
 * Skip skips a hook step that is running.
 */
export function Skip(stepID: string): $CancellablePromise<void> {
    return $Call.ByID(3397059930, stepID);
}
