// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as achievements$0 from "../achievements/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syncer$0 from "../syncer/models.js";

/**
 * Accounts are the store accounts owned games come from.
 */
export interface Accounts {
    "steam": StoreAccount;
    "gog": StoreAccount;
    "epic": StoreAccount;

    /**
     * GOGSignIn is the GOG account signed in for achievements (GOG
     * Galaxy's library, above, needs no sign-in).
     */
    "gogSignIn": StoreAccount;
}

/**
 * AppInfo describes this build.
 */
export interface AppInfo {
    "version": string;
    "dataDir": string;
    "logFile": string;

    /**
     * The previous run crashed (its output is in crash-previous.log).
     */
    "crashedLastTime": boolean;
}

/**
 * MetaState is what the metadata worker is doing.
 */
export interface MetaState {
    "running": boolean;
    "done": number;
    "total": number;
}

/**
 * PadAction is one controller action.
 */
export interface PadAction {
    "action": string;
    "repeat": boolean;
}

/**
 * Saves is what Syncer knows about a game's saves, for the interface.
 */
export interface Saves {
    /**
     * Syncer is installed
     */
    "installed": boolean;

    /**
     * too old for the launcher API
     */
    "outdated": boolean;

    /**
     * Syncer answered
     */
    "available": boolean;
    "error"?: string;

    /**
     * Syncer has save folders for this game
     */
    "known": boolean;
    "folders": syncer$0.Folder[] | null;
}

/**
 * ScanState tells the frontend what the scanner is doing.
 */
export interface ScanState {
    "running": boolean;

    /**
     * unix seconds
     */
    "lastScan": number;
    "tookMs": number;
    "games": number;
    "added": number;

    /**
     * titles in the game database; 0 until it's downloaded
     */
    "known": number;
    "error"?: string;
}

/**
 * SessionAchievements are the achievements one session unlocked.
 */
export interface SessionAchievements {
    "gameId": number;
    "title": string;
    "unlocked": achievements$0.Achievement[] | null;
}

/**
 * StoreAccount is one store account as Settings shows it.
 */
export interface StoreAccount {
    "connected": boolean;

    /**
     * the store is on this PC (GOG: Galaxy's library)
     */
    "available": boolean;
    "name"?: string;
    "games": number;

    /**
     * unix seconds
     */
    "synced"?: number;
    "syncing": boolean;
    "error"?: string;
}

/**
 * SyncerStatus is how Seaglass and Syncer get on, for Settings.
 */
export interface SyncerStatus {
    "installed": boolean;
    "version"?: string;

    /**
     * too old for the launcher API
     */
    "outdated": boolean;

    /**
     * Syncer answered
     */
    "connected": boolean;

    /**
     * its launcher API is up (it may not have been asked to start)
     */
    "running": boolean;
    "error"?: string;

    /**
     * its sync engine runs
     */
    "syncing": boolean;
    "paused": boolean;
    "pausedUntil"?: number;
    "backingUp": boolean;
    "lastBackup"?: number;
    "games": number;
    "conflicts": number;
    "checkedAt": number;
}

/**
 * UpdateState is what the interface shows about updates.
 */
export interface UpdateState {
    "current": string;
    "latest"?: string;
    "status": string;

    /**
     * 0 to 1 while downloading
     */
    "progress": number;
    "notes"?: string;
    "page": string;
    "error"?: string;

    /**
     * unix seconds
     */
    "checkedAt": number;

    /**
     * Failed: an install of Latest was started before but this is still
     * the old version, so it isn't retried on its own.
     */
    "failed": boolean;
}
