// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfileService is who's playing, for the interface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns the last known state; fresh asks Syncer first (without
 * starting it).
 */
export function Get(fresh: boolean): $CancellablePromise<$models.Profile> {
    return $Call.ByID(1004510423, fresh);
}

/**
 * Switch makes another of Syncer's accounts the one playing on this PC:
 * Syncer puts their saves in place, and Seaglass shows their playtime,
 * achievements and settings.
 */
export function Switch(id: string): $CancellablePromise<$models.Profile> {
    return $Call.ByID(2438384625, id);
}
