// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Achievement is one achievement as the interface shows it.
 */
export interface Achievement {
    "id": string;
    "name": string;
    "desc"?: string;

    /**
     * https URL or a local file; the interface gets /ach/ URLs
     */
    "icon"?: string;

    /**
     * the locked icon
     */
    "iconGray"?: string;
    "hidden"?: boolean;
    "unlocked": boolean;

    /**
     * unix seconds; 0 when unlocked at an unknown time
     */
    "unlockedAt"?: number;
    "progress"?: number;
    "max"?: number;

    /**
     * share of all players who have it (Steam's global stats)
     */
    "percent"?: number | null;
}

/**
 * List is a game's achievements.
 */
export interface List {
    "gameId": number;

    /**
     * "steam", "epic", "gog", "Goldberg", "CODEX", …; "" when none was found
     */
    "source": string;
    "total": number;
    "unlocked": number;
    "items": Achievement[] | null;
    "updatedAt": number;

    /**
     * what's missing, and how to get it
     */
    "hint"?: string;
}
