// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Account is one person with their own saves in Syncer.
 */
export interface Account {
    "id": string;
    "name": string;
    "color"?: string;
    "active": boolean;
}

/**
 * Folder is one save folder Syncer looks after.
 */
export interface Folder {
    "id": string;
    "label": string;
    "path": string;
    "sync": boolean;
    "backup": boolean;
    "state": string;
    "needBytes": number;
    "errors": number;
    "conflicts": number;
    "exists": boolean;
    "modified": string;
    "backedUp": string;
    "newerOn": string;
    "newerAt": string;

    /**
     * Account: the game has separate saves per account, and this folder
     * holds the saves of the account playing on this PC.
     */
    "account"?: string;
}
