// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Choice is one picture a game's art can be changed to: already stored
 * (the interface only shows local art), with where it came from.
 */
export interface Choice {
    /**
     * /art/… URL
     */
    "art": string;
    "source": string;
    "width": number;
    "height": number;
}

/**
 * StoreHit is one result of a Steam store search.
 */
export interface StoreHit {
    "appId": number;
    "name": string;

    /**
     * small capsule on Steam's CDN (not fetched by WaterLauncher)
     */
    "image": string;
}
